# Generated by Django 5.0.2 on 2024-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_autos_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=70)),
                ('consola', models.CharField(max_length=30)),
                ('version', models.FloatField()),
                ('fecha_lanzamiento', models.DateField()),
                ('compania', models.CharField(max_length=30)),
            ],
        ),
    ]
