# Generated by Django 5.0.2 on 2024-03-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_juego_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
